import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import AccountForm from "./components/AccountForm";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Expiration App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">
          <Link href="/cart">Cart</Link>
        </h1>

        <AccountForm></AccountForm>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/gavinshelley3/FoodApp"
          target="_blank"
          rel="noopener noreferrer"
        >
          Github Repo
        </a>
      </footer>
    </div>
  );
}
